xml_atmos_base_ddp = """<?xml version="1.0"?>
<job_config>
  <input>
    <audio>
      <atmos_mezz version="1">
        <file_name>-</file_name>
        <timecode_frame_rate>-</timecode_frame_rate>
        <offset>auto</offset>
        <ffoa>auto</ffoa>
        <storage>
          <local>
            <path>-</path>
          </local>
        </storage>
      </atmos_mezz>
    </audio>
  </input>
  <filter>
    <audio>
      <encode_to_atmos_ddp version="1">
        <loudness>
          <measure_only>
            <metering_mode>1770-4</metering_mode>
            <dialogue_intelligence>true</dialogue_intelligence>
            <speech_threshold>15</speech_threshold>
          </measure_only>
        </loudness>
        <data_rate>-</data_rate>
        <timecode_frame_rate>-</timecode_frame_rate>
        <start>first_frame_of_action</start>
        <end>end_of_file</end>
        <time_base>file_position</time_base>
        <prepend_silence_duration>0.0</prepend_silence_duration>
        <append_silence_duration>0.0</append_silence_duration>
        <drc>
          <line_mode_drc_profile>-</line_mode_drc_profile>
          <rf_mode_drc_profile>-</rf_mode_drc_profile>
        </drc>
        <downmix>
          <loro_center_mix_level>-3</loro_center_mix_level>
          <loro_surround_mix_level>-3</loro_surround_mix_level>
          <ltrt_center_mix_level>-3</ltrt_center_mix_level>
          <ltrt_surround_mix_level>-3</ltrt_surround_mix_level>
          <preferred_downmix_mode>-</preferred_downmix_mode>
        </downmix>
        <custom_trims>
          <surround_trim_5_1>auto</surround_trim_5_1>
          <height_trim_5_1>auto</height_trim_5_1>
        </custom_trims>
        <encoding_backend>-</encoding_backend>
        <encoder_mode>-</encoder_mode>
      </encode_to_atmos_ddp>
    </audio>
  </filter>
  <output>
    <ec3 version="1">
      <file_name>-</file_name>
      <storage>
        <local>
          <path>-</path>
        </local>
      </storage>
    </ec3>
  </output>
  <misc>
    <temp_dir>
      <clean_temp>true</clean_temp>
      <path>-</path>
    </temp_dir>
  </misc>
</job_config>"""
