atmos_channels = {
    "2.0": {
        "id": 0,
        "names": ["L", "R"],
    },
    "3.1": {
        "id": 3,
        "names": ["L", "R", "C", "LFE"],
    },
    "5.1": {
        "id": 7,
        "names": ["L", "R", "C", "LFE", "Ls", "Rs"],
    },
    "7.1": {
        "id": 11,
        "names": ["L", "R", "C", "LFE", "Ls", "Rs", "Lrs", "Rrs"],
    },
    "9.1": {
        "id": 12,
        "names": ["L", "R", "C", "LFE", "Ls", "Rs", "Lrs", "Rrs", "Lw", "Rw"],
    },
    "5.1.2": {
        "id": 13,
        "names": ["L", "R", "C", "LFE", "Ls", "Rs", "Ltm", "Rtm"],
    },
    "5.1.4": {
        "id": 14,
        "names": ["L", "R", "C", "LFE", "Ls", "Rs", "Ltf", "Rtf", "Ltr", "Rtr"],
    },
    "7.1.2": {
        "id": 15,
        "names": ["L", "R", "C", "LFE", "Ls", "Rs", "Lrs", "Rrs", "Ltm", "Rtm"],
    },
    "7.1.4": {
        "id": 16,
        "names": [
            "L",
            "R",
            "C",
            "LFE",
            "Ls",
            "Rs",
            "Lrs",
            "Rrs",
            "Ltf",
            "Rtf",
            "Ltr",
            "Rtr",
        ],
    },
    "7.1.6": {
        "id": 17,
        "names": [
            "L",
            "R",
            "C",
            "LFE",
            "Ls",
            "Rs",
            "Lrs",
            "Rrs",
            "Ltf",
            "Rtf",
            "Ltm",
            "Rtm",
            "Ltr",
            "Rtr",
        ],
    },
    "9.1.2": {
        "id": 18,
        "names": [
            "L",
            "R",
            "C",
            "LFE",
            "Ls",
            "Rs",
            "Lrs",
            "Rrs",
            "Lw",
            "Rw",
            "Ltm",
            "Rtm",
        ],
    },
    "9.1.4": {
        "id": 19,
        "names": [
            "L",
            "R",
            "C",
            "LFE",
            "Ls",
            "Rs",
            "Lrs",
            "Rrs",
            "Lw",
            "Rw",
            "Ltf",
            "Rtf",
            "Ltr",
            "Rtr",
        ],
    },
    "9.1.6": {
        "id": 20,
        "names": [
            "L",
            "R",
            "C",
            "LFE",
            "Ls",
            "Rs",
            "Lrs",
            "Rrs",
            "Lw",
            "Rw",
            "Ltf",
            "Rtf",
            "Ltm",
            "Rtm",
            "Ltr",
            "Rtr",
        ],
    },
}
