xml_audio_base_atmos = """<?xml version="1.0"?>
<job_config>
  <input>
    <audio>
      <thd version="1">
        <file_name>-</file_name>
        <timecode_frame_rate>not_indicated</timecode_frame_rate>
        <offset>auto</offset>
        <ffoa>auto</ffoa>
        <storage>
          <local>
            <path>-</path>
          </local>
        </storage>
      </thd>
    </audio>
  </input>
  <filter>
    <audio>
      <encode_to_atmos_ddp version="1">
        <input_channel_layout>7.1.2</input_channel_layout>
        <data_rate>1500</data_rate>
        <timecode_frame_rate>not_indicated</timecode_frame_rate>
        <start>first_frame_of_action</start>
        <end>end_of_file</end>
        <time_base>file_position</time_base>
        <prepend_silence_duration>0.0</prepend_silence_duration>
        <append_silence_duration>0.0</append_silence_duration>
        <custom_trims>
          <surround_trim_5_1>0.0</surround_trim_5_1>
          <height_trim_5_1>0.0</height_trim_5_1>
        </custom_trims>
      </encode_to_atmos_ddp>
    </audio>
  </filter>
  <output>
    <ec3 version="1">
      <file_name>-</file_name>
      <storage>
        <local>
          <path>-</path>
        </local>
      </storage>
    </ec3>
  </output>
  <misc>
    <temp_dir>
      <clean_temp>true</clean_temp>
      <path>-</path>
    </temp_dir>
  </misc>
</job_config>"""