name: Deploy MkDocs on release

on:
  release:
    types: [published]

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    # only run for non-prerelease/non-draft releases that target the main branch
    if: >
      github.event.release.prerelease == false &&
      github.event.release.draft == false &&
      github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Build site
        run: mkdocs build

      - name: Configure git for deploy
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
