name: PyPI

on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and publish (useful for manual RC builds). If omitted, defaults to main. For release events the tag will be used."
        required: false
        default: "main"

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/deezy/

    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # If triggered by a release use the release tag, otherwise use the
          # supplied workflow_dispatch `branch` input (or default to 'main').
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.branch || 'main' }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: python -m pip install --upgrade uv

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install build tools
        run: . .venv/bin/activate && uv pip install twine

      - name: Build the package
        run: . .venv/bin/activate && uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
