name: Build and Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            executable: deezy
            artifact_name: deezy-linux-x64
          - os: macos-latest
            platform: macos
            executable: deezy
            artifact_name: deezy-macos-x64
          - os: windows-latest
            platform: windows
            executable: deezy.exe
            artifact_name: deezy-windows-x64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --group dev --group build

      - name: Run tests
        run: uv run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Build executable
        run: uv run python build.py

      - name: Verify build output
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" == "windows" ]; then
            ls -la pyinstaller_build/dist/
            if [ ! -f "pyinstaller_build/dist/deezy.exe" ]; then
              echo "Build failed: deezy.exe not found"
              exit 1
            fi
          else
            ls -la pyinstaller_build/dist/
            if [ ! -f "pyinstaller_build/dist/deezy" ]; then
              echo "Build failed: deezy executable not found"
              exit 1
            fi
          fi

      - name: Create ZIP archive (Windows)
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          cd pyinstaller_build/dist/
          Compress-Archive -Path deezy.exe -DestinationPath ../../${{ matrix.artifact_name }}.zip -CompressionLevel Optimal

      - name: Create ZIP archive (Unix)
        if: matrix.platform != 'windows'
        shell: bash
        run: |
          cd pyinstaller_build/dist/
          zip -9 ../../${{ matrix.artifact_name }}.zip deezy

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.zip
          retention-days: 7

  release:
    name: Create Release Assets
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload release assets
        run: |
          set -e  # Exit on any error

          echo "=== File sizes ==="
          ls -lh ./*/*.zip

          echo "=== Uploading Linux ZIP ==="
          gh release upload ${{ github.event.release.tag_name }} \
            ./deezy-linux-x64/deezy-linux-x64.zip \
            --repo ${{ github.repository }} \
            --clobber
          echo "✅ Linux ZIP uploaded successfully"

          echo "=== Uploading macOS ZIP ==="
          gh release upload ${{ github.event.release.tag_name }} \
            ./deezy-macos-x64/deezy-macos-x64.zip \
            --repo ${{ github.repository }} \
            --clobber
          echo "✅ macOS ZIP uploaded successfully"

          echo "=== Uploading Windows ZIP ==="
          gh release upload ${{ github.event.release.tag_name }} \
            ./deezy-windows-x64.exe/deezy-windows-x64.exe.zip \
            --repo ${{ github.repository }} \
            --clobber
          echo "✅ Windows ZIP uploaded successfully"

          echo "🎉 All ZIP archives uploaded successfully!"

          echo "=== Final Release Assets ==="
          gh release view ${{ github.event.release.tag_name }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
