name: ruff

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Create venv and install ruff
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          # Use the venv python explicitly for subsequent installs
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install ruff

      - name: Check imports + format (via venv python, non-modifying)
        run: |
          # Run ruff using the project's pyproject.toml include/select settings.
          # `--select-from` will read the config and apply the include globs
          # we set in [tool.ruff] (see pyproject.toml).
          .venv/bin/python -m ruff check --select-from pyproject.toml
          .venv/bin/python -m ruff format --check --select-from pyproject.toml
